### ISSUE TITLE
Support extra options for validate hooks

### ISSUE THREAD

**Issue by anotherminh** [transcend-io/wildebeest#76]
Currently it is possible to pass along extra information for the create/update/destroy hooks:
```
  /** The additional types that Sequelize hooks are expecting */
  public hookOptionsT: {
    create: {
      optionOne: number;
      optionTwo?: string;
    };
```

However, it isn't possible to do this for the validate hooks.

**Comment by michaelfarrell76** [comment]
ya would be nice, the complexity is that the validate hook is called before all of create, update, delete so its a bit hard to get it to get perfect typing. Its not really the union, best chance may be to union and make partial
